config/routes.rb
Rails.application.routes.draw do

	root 'shops#find'

	get '/shops/find', to: 'shops#find'

	resources :shops

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
	validates :name, length: { minimum: 8 }, presence: true
	validates :address, length: { minimum: 8 }, presence: true
	
	validates :latitude, length: { minimum: 4 }, 
	  presence: true, format: { with: /\A\-?\d+\.\d+\z/,
      message: "only allows geographic coordinates" }

  validates :longitude, length: { minimum: 4 }, 
   	presence: true, format: { with: /\A\-?\d+\.\d+\z/,
       message: "only allows geographic coordinates" }

  validates :chain, presence: true
  validates :city, presence: true
  validates :zip, presence: true, length: { is: 5}, numericality: { only_integer: true }
  validates :phone, presence: true, length: { is: 10}, numericality: { only_integer: true }
  validates :country_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def find
    if !request.location.latitude.blank?
      @shops = helpers.find_with_user_position(request.location.latitude, request.location.longitude)
    else  
      @shops = helpers.find_with_filter(params)
    end
  end

  def index  
    @shops = helpers.finder(params)    
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new
    @shop.chain = "shopmium"
    @shop.name = params["shop"]["name"]
    @shop.address = params["shop"]["address"]
    @shop.city = params["shop"]["city"]
    @shop.phone = params["shop"]["phone"]
    @shop.zip = params["shop"]["zip"]
    @shop.country_code = params["shop"]["country_code"]
    @shop.latitude = params["shop"]["latitude"]
    @shop.longitude = params["shop"]["longitude"]
    if @shop.save
      flash[:success] = "Shop succesfully added !"
      redirect_to shops_path
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params["id"])
  end

  def update
    @shop = Shop.find(params["id"])
    if @shop.update(name: params["shop"]["name"], address: params["shop"]["address"],
      city: params["shop"]["city"], phone: params["shop"]["phone"], zip: params["shop"]["zip"],
      country_code: params["shop"]["country_code"], latitude: params["shop"]["latitude"],
      longitude: params["shop"]["longitude"])
      flash[:success] = "Shop succesfully edited !"
      redirect_to shops_path
    else
      render :edit
    end
  end

  def destroy
    if Shop.find(params["id"]).delete then flash[:success] = "Shop succesfully deleted !" and redirect_to shops_path end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
  include Math

  def finder(params)
  	array = []
    if !params["place"].blank?
      place = params["place"].delete("*+/\\_()[]{}\"#~@°%$;:!?") 
      Shop.where("city ~* ?", "#{place}").each do |s| array << s end
      Shop.where("address ~* ?", "#{place}").each do |s| array << s end
      Shop.where("zip ~* ?", "#{place}").each do |s| array << s end
	elsif !params["t"].blank?
	  case params["t"]
	    when '0'
	      array = Shop.all.order(:created_at)
		when '1'
		  array = Shop.all.order(created_at: :desc)
		when '2'
		  array = Shop.all.order(updated_at: :desc)
		end
	else
	 array = Shop.all
	end
	return array
  end

  def find_with_filter(params)
  	if params["position"].blank?
  		return nil
  	elsif Geocoder.search(params["position"]).blank?
  		return nil
  	elsif params["km"].blank?
  		params["km"] = 20
  	end
  	position = Geocoder.search(params["position"]).first.coordinates
  	lat1 = position[0]
  	lon1 = position[1]
  	
  	array = []
  	Shop.all.each do |shop|
  	  lat2 = shop.latitude.to_f
  	  lon2 = shop.longitude.to_f

  	  if distance(lat1, lon1, lat2, lon2) <= params["km"].to_i + 2
  	  	array << shop
  	  end  
  	end
  	return array
  end

  def find_with_user_position(lat, lon)
  	lat1 = lat.to_f
  	lon1 = lon.to_f
  	
  	array = []
  	Shop.all.each do |shop|
  	  lat2 = shop.latitude.to_f
  	  lon2 = shop.longitude.to_f

  	  if distance(lat1, lon1, lat2, lon2) <= params["km"].to_i + 2
  	  	array << shop
  	  end  
  	end
  	return array
  end

  def distance(lat1, lon1, lat2, lon2)
    r = 6366
  	lat1 = lat1 * PI / 180 #deg2rad
  	lon1 = lon1 * PI / 180 #deg2rad
  	lat2 = lat2 * PI / 180 #deg2rad
  	lon2 = lon2 * PI / 180 #deg2rad

  	def pow(x,y)
  		x ** y
  	end

  	f = 2 * asin(sqrt(pow( sin((lat1-lat2)/2) , 2) + cos(lat1)*cos(lat2)* pow( sin((lon1-lon2)/2) , 2)))
  	km = f * r
  	return km
  end
  # R * pi * sqrt((x1-x2)²+(y1-y2²)/180)
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestForShopmium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/components/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/components/_navbar.html.erb
<nav class="navbar navbar-dark" style="background-color: #f01f74;">
  <%= link_to "Find Shops", shops_find_path, class: 'navbar-brand' %>
  <div><%= link_to "All Shops", shops_path, class: 'navbar-brand' %>
  <%= link_to "Add Shop", new_shop_path, class: 'navbar-brand' %></div>
</nav>

<% flash.each do |message_type, message| %>
  <% if message_type == "success" %>
    <div class="alert alert-<%=message_type%>" style="text-align: center; margin-bottom: 0;">
  <% else %>
    <div class="alert alert-<%=message_type%>" style="text-align: center; margin-bottom: 0;">
  <% end %>
      <%= message %>
    </div>
<% end %>

app/views/shops/_error.html.erb
<% if !@shop.errors.details[f].blank? %>
  
  <p class="alert alert-danger"> <%= f %>

    <% @shop.errors.messages[f].each do |msg| %>
    
      <%= msg %>
  
    <% end %></p>
<% end %>

app/views/shops/_results.html.erb
	<div class="row">	  
    
    <div id="result" class="col" style="">	
      
      <% if @shops.blank? %>
        <h2>Aucun shop trouvé.</h2>
      <% else %>
        
        <table class="table table-hover">
           
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Address</th>
              <th scope="col">Phone</th>
            </tr>
          </thead>

          <% @shops.each do |shop| %>

            <tr class="shop" data-lat="<%=shop.latitude%>" data-long="<%= shop.longitude %>" data-nom="<%= shop.name %>">
              <td> <%= shop.name %> </td>
              <td> <%= shop.address %> </td>
              <td> <%= shop.phone %> </td>
            </tr>
       
          <% end %>
       
        </table>
     
      <% end %>
    
    </div>

    <div id="map" class="col-6" style="height: 650px;">

  </div>

app/views/shops/_search_form.html.erb
<form action="/shops/find" method="get">
	
	<div class="form-row justify-content-md-center" style="margin-bottom: 20px;">
	    
	  <div class="form-group col col-lg-5">
	    <label for="position">Votre position</label>
	    <input type="text" id="position" name="position" class="form-control" placeholder="Adresse, ville ou code postal">
	  </div>
	    
	  <div class="form-group col-auto">
	    <label for="km">Tout les shops dans un rayon de .. km</label>
	    <input type="text" id="km" name="km" class="form-control" value="20">
	  </div>
	    
	  <div class="col-auto" style="margin-top: 31px;">
	    <button type="submit" class="btn btn-dark">Rechercher</button>
	  </div>

	</div>

</form>

app/views/shops/edit.html.erb
<center><h1>Edit a shop</h1></center>

<%= form_for @shop do |f| %>
		  
	<div class="form-row justify-content-md-center">
		 
		<div class="form-group col col-lg-4">
		    <%= f.label :name %>
		    <%= f.text_field :name, required: true, class: "form-control" %>
		    <%= render 'error', :@shop => @shop, :f => :name %>
		</div>

		<div class="form-group col col-lg-4">
		    <%= f.label :address %>
		    <%= f.text_field :address, required: true, class: "form-control"  %>
		    <%= render 'error', :@shop => @shop, :f => :address %>
		</div>
	</div>

	<div class="form-row justify-content-md-center">
		    	  
		<div class="form-group col col-lg-4">
		    <%= f.label :city %>
		    <%= f.text_field :city, required: true, class: "form-control"  %><br>
		    <%= render 'error', :@shop => @shop, :f => :city %>
		</div>
		    	  
		<div class="form-group col col-lg-4">
		    <%= f.label :zip %>
		    <%= f.text_field :zip, required: true, class: "form-control"  %>
		    <%= render 'error', :@shop => @shop, :f => :zip %>
		</div>
	</div>

	<div class= "form-row justify-content-md-center">
		
		<div class="form-group col col-lg-4">
			<%= f.label :country_code %>
			<%= f.text_field :country_code, required: true, class: "form-control"  %>
			<%= render 'error', :@shop => @shop, :f => :country_code %>
		</div>
				  
		<div class="form-group col col-lg-4">
			<%= f.label :phone %>
			<%= f.text_field :phone, required: true, class: "form-control"  %>
			<%= render 'error', :@shop => @shop, :f => :phone %>
		</div>
	</div>

	<div class="form-row justify-content-md-center">
		 	    
		<div class="form-group col col-lg-4">
		 	<%= f.label :latitude %>
		 	<%= f.text_field :latitude, required: true, class: "form-control"  %>
		 	<%= render 'error', :@shop => @shop, :f => :latitude %>
		</div>

		<div class="form-group col col-lg-4">
		 	<%= f.label :longitude %>
		 	<%= f.text_field :longitude, required: true, class: "form-control"  %>
		 	<%= render 'error', :@shop => @shop, :f => :longitude %>
		</div>
	</div>

		<div class="form-row justify-content-md-center" ><%= f.submit "Edit", class: "btn btn-dark"%>

	</div>

<% end %>

app/views/shops/find.html.erb
<head>
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
   integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
   crossorigin=""/>
</head>

<div id="infoposition"></div>

<div id="shop_find" class="container-fluid">

  <% if params["position"].blank? %>
    
    <center><h1 style="margin-top: 150px;">Trouver un magasin</h1></center>
    <%= render 'search_form' %>

  <% else %>

    <center><h1 style="margin-top: 10px;">Trouver un magasin</h1></center>
    <%= render 'search_form' %>
    <%= render 'results', :@shops => @shops %>

  <% end%>

</div>

<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
   integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
   crossorigin=""></script>

<script type="text/javascript">
	$( document ).ready(function() {

	let map = document.querySelector('#map')

	if (map !== null) {

		let map = L.map('map').setView([46.78054940133053, 2.6491201250000813], 6);

		L.tileLayer('//{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
		    attribution: 'donn&eacute;es &copy; <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu <a href="//openstreetmap.fr">OSM France</a>',
		    maxZoom: 18
		}).addTo(map);

		Array.from(document.querySelectorAll('.shop')).forEach((shop) => {
			L.marker([shop.dataset.lat, shop.dataset.long]).addTo(map).bindPopup(shop.dataset.nom);
		})
	}
	});
</script>

app/views/shops/index.html.erb
  	<form action="/shops" method="get">
  	  <div class="form-row justify-content-md-center" style="margin-bottom: 10px;margin-top: 15px;">
  	    <div class="form-group col col-lg-5">
  	      <label for="place">Address, city, or zip</label>
  	      <input type="text" id="place" name="place" class="form-control" placeholder="Paris">
  	    </div>
  	    <div class="col-auto" style="margin-top: 31px;">
  	    	<button type="submit" class="btn btn-dark">Search</button>
  	    </div>
  	  </div>
  	</form>

  	<div class="row justify-content-md-center" style="margin-bottom: 25px;">
	  <div class="col-auto">
	  	<%= link_to "First added", "/shops?t=0", class: "btn btn-outline-dark" %>
	  </div>
	  <div class="col-auto">
	    <%= link_to "Last added", "/shops?t=1", class: "btn btn-outline-dark" %>
	  </div>
	  <div class="col-auto">
  		<%= link_to "Last edited", "/shops?t=2", class: "btn btn-outline-dark" %>
  	  </div>
  	</div>

<div id="results_table">
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th scope="col">Name</th>
	      <th scope="col">Address</th>
	      <th scope="col">Phone</th>
	      <th scope="col">Zip</th>
	      <th scope="col">Last edit</th>
	      <th scope="col">Date added</th>
	      <th scope="col">Edit</th>
	      <th scope="col">Delete</th>
	    </tr>
	  </thead>
	  <% @shops.each do |shop| %>

	    <tr>
	      <td> <%= shop.name %> </td>
	      <td> <%= shop.address %> </td>
	      <td> <%= shop.phone %> </td>
	      <td> <%= shop.zip %> </td>
	      <td> <%= shop.updated_at.to_s.delete('UTC') %> </td>
	      <td> <%= shop.created_at.to_s.delete('UTC') %> </td>
	      <td> <%= link_to "Edit", edit_shop_path(shop), class: "btn btn-outline-success" %> </td>
	      <td> <%= link_to "Delete", shop_path(shop), method: :delete , class: "btn btn-outline-danger" %> </td>
	    </tr>
	  
	  <% end %>
	</table>
</div>

app/views/shops/new.html.erb
<center><h1>Add a new shop</h1></center>

    <%= form_for @shop do |f| %>
      <div class="form-row justify-content-md-center">
      	      <div class="form-group col col-lg-4">
      			<%= f.label :name %>
      			<%= f.text_field :name, placeholder: "Shopmium Paris", required: true, class: "form-control" %>
      			<%= render 'error', :@shop => @shop, :f => :name %>
      		  </div>

      		  <div class="form-group col col-lg-4">
      			<%= f.label :address %>
      			<%= f.text_field :address, placeholder: "69 rue de Rennes", required: true, class: "form-control"  %>
      			<%= render 'error', :@shop => @shop, :f => :address %>
      		  </div>
      </div>

    <div class="form-row justify-content-md-center">
    	  <div class="form-group col col-lg-4">
    		<%= f.label :city %>
    		<%= f.text_field :city, placeholder: "Paris", required: true, class: "form-control"  %><br>
    		<%= render 'error', :@shop => @shop, :f => :city %>
    	  </div>
    	  <div class="form-group col col-lg-4">
    	  	<%= f.label :zip %>
    	  	<%= f.text_field :zip, placeholder: "95000", required: true, class: "form-control"  %>
    	  	<%= render 'error', :@shop => @shop, :f => :zip %>
    	  </div>
    </div>

	<div class= "form-row justify-content-md-center">
		  <div class="form-group col col-lg-4">
			<%= f.label :country_code %>
			<%= f.text_field :country_code, placeholder: "fr", required: true, class: "form-control"  %>
		    <%= render 'error', :@shop => @shop, :f => :country_code %>
		  </div>
		  <div class="form-group col col-lg-4">
		    <%= f.label :phone %>
		    <%= f.text_field :phone, placeholder: "0467761330", required: true, class: "form-control"  %>
		    <%= render 'error', :@shop => @shop, :f => :phone %>
		  </div>
	</div>

	<div class="form-row justify-content-md-center">
 	    <div class="form-group col col-lg-4">
 	  	<%= f.label :latitude %>
 	  	<%= f.text_field :latitude, placeholder: "43.4592", required: true, class: "form-control"  %>
 	  	<%= render 'error', :@shop => @shop, :f => :latitude %>
 	    </div>

 	    <div class="form-group col col-lg-4">
 	  	<%= f.label :longitude %>
 	  	<%= f.text_field :longitude, placeholder: "3.689298", required: true, class: "form-control"  %>
 	  	<%= render 'error', :@shop => @shop, :f => :longitude %>
 	    </div>
	</div>

	<div class="form-row justify-content-md-center" ><%= f.submit "Add", class: "btn btn-dark"%>
</div>

<% end %>